---
title: Ramificação saindo de uma 'Finally' é inválida
ms.date: 07/20/2015
f1_keywords:
- bc30101
- vbc30101
helpviewer_keywords:
- BC30101
ms.assetid: 16a0dc29-3657-4373-b77f-38f3cb80e6c9
ms.openlocfilehash: 7d9a77f90148c62fbfef34edee4a914882573b2e
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 06/04/2020
ms.locfileid: "84359420"
---
# <a name="branching-out-of-a-finally-is-not-valid"></a>Ramificação saindo de uma 'Finally' é inválida
Uma `GoTo` instrução dentro de um `Finally` bloco ramifica fora do bloco. Não é válido ramificar para dentro ou para fora de `Catch` um `Finally` bloco ou.  
  
 **ID do erro:** BC30101  
  
## <a name="to-correct-this-error"></a>Para corrigir este erro  
  
- Remova a `GoTo` instrução e considere implementar a lógica do programa com estruturas de controle de decisão ou loop.  
  
## <a name="see-also"></a>Confira também

- [Instrução Try...Catch...Finally](../language-reference/statements/try-catch-finally-statement.md)
- [Instrução GoTo](../language-reference/statements/goto-statement.md)
- [Fluxo de controle](../programming-guide/language-features/control-flow/index.md)
