---
title: O operando 'Throw' deve ser derivado de 'System.Exception'
ms.date: 07/20/2015
f1_keywords:
- vbc30665
- bc30665
helpviewer_keywords:
- BC30665
ms.assetid: 7c228087-39ea-4b30-a410-6ba711e67e5e
ms.openlocfilehash: 92fccbd2faac5580d28fef8cc02b51b23715f136
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 06/04/2020
ms.locfileid: "84414940"
---
# <a name="throw-operand-must-derive-from-systemexception"></a>O operando 'Throw' deve ser derivado de 'System.Exception'
O argumento fornecido `Throw` deve ser uma instância do `System.Exception` ou uma instância de uma classe derivada de `System.Exception` .  
  
 **ID do erro:** BC30665  
  
## <a name="to-correct-this-error"></a>Para corrigir este erro  
  
- Use um argumento derivado de `System.Exception` , como no exemplo a seguir.  
  
    ```vb
    Throw New System.Exception("This is an error.")  
    ```  
  
## <a name="see-also"></a>Confira também

- [Instrução Throw](../language-reference/statements/throw-statement.md)
- [Instrução Try...Catch...Finally](../language-reference/statements/try-catch-finally-statement.md)
- <xref:System.Exception?displayProperty=nameWithType>
- [Tratando e gerando exceções no .NET](../../standard/exceptions/index.md)
